sudo: required
services:
    - docker
before_install:
    - docker build -t jessevogt/mke-python-demo-get-my-ip:$TRAVIS_COMMIT .
script:
    - docker run --rm jessevogt/mke-python-demo-get-my-ip:$TRAVIS_COMMIT pytest